export const PALESTINE_NAMES = [
    'Ghassan Kanafani',
    'Mahmoud Darwish',
    'Naji al-Ali',
    'Haji Amin al-Husseini',
    'Izz ad-Din al-Qassam',
    'Dalal Mughrabi',
    'Rachel Corrie',
    'Shireen Abu Akleh',
    'Al-Quds',
    'Gaza',
    'Ramallah',
    'Jaffa',
    'Haifa',
    'Hebron',
    'Nablus',
    'Jenin',
    'Freedom Fighter',
    'Land of Olives',
    'Hope of Return',
    'Palestinian Soul',
    'Resilient Gaza',
    'Voice of Freedom',
    'Olive Branch',
    'Handala',
]
